### ISSUE TITLE
Merge `Client` and `TestSuite`?

### ISSUE THREAD

**Issue by larry0x** [left-curve/left-curve#127]
These two have very similar APIs and share a lot of code. Which isn't surprising - if you think about it, the `TestSuite` is basically a client interacting with an in-process `App`. We can think about whether we can merge them into one.

**Comment by Rhaki** [comment]
Good point. Anyway merging them could be very challenging because they have similar concept but with some differences (for example, on `Client` all functions are
`asynchronous`). We could try to build `TestSuite` above `Client`, abstracting the `App` with a `Trait`. `Client` will have a generic params of this Trait, that in case of standard client, the inner type will connect to the `tendermint`, instead for test will contains the `App` itself.

Not super easy anyway
